### ISSUE TITLE
Not a issue, A solution

### ISSUE THREAD

**Issue by 0FGAW4FGYWAO23YGWAFO2Y5W5GYUAWU1YFT4AFF** [RbxGen/RobloxGen#34]
if you want to fix the horrible formating do this:

open the file in notepad ++
check "extended (\n, \r, \t, \0, \x...)"
then press replace and type this EXACTLY:
find what : {"username"
replace with \n {"username"
it should put a line between every account 😁

**Comment by jluims** [comment]
👍

**Comment by jluims** [comment]
or you can use this https://codebeautify.org/jsonviewer
(p.s. this is sort of irrelevant to the issue as they just wanted username:password:cookie format instead of JSON)
