### ISSUE TITLE
Make it send the accounts info to discord via webhook

### ISSUE THREAD

**Issue by SlotthCode** [RbxGen/RobloxGen#36]
if you can

**Comment by ducksquaddd** [comment]
I can probably set this up and send a pr soonish, unless one of the maintainers of this project want to do it themselves

**Comment by SlotthCode** [comment]
do you discord ? add SlotthVFX#7496

**Comment by jluims** [comment]
ok ill do it

**Comment by SlotthCode** [comment]
ty
