### ISSUE TITLE
Proxy rotated error

### ISSUE THREAD

**Issue by mstudio45** [RbxGen/RobloxGen#41]
I have valid proxies and i get this error.  
![Screenshot_20220425-060410_Chrome](https://user-images.githubusercontent.com/69036065/165019014-a6a923f1-04ce-49d5-a108-49d6966d723a.jpg)
How to fix it this issue?

**Comment by jluims** [comment]
the proxy feature is pretty unstable. though the error means you have to update your nodejs

**Comment by rbxlscripts** [comment]
> the proxy feature is pretty unstable. though the error means you have to update your nodejs

Thank you so much! It works now. :)

**Comment by jluims** [comment]
> > the proxy feature is pretty unstable. though the error means you have to update your nodejs
> 
> Thank you so much! It works now. :)

wait like the proxy system actually works? i could never get it to work myself lol. maybe my proxies are just bad

**Comment by ducksquaddd** [comment]
> > > the proxy feature is pretty unstable. though the error means you have to update your nodejs
> > 
> > 
> > Thank you so much! It works now. :)
> 
> wait like the proxy system actually works? i could never get it to work myself lol. maybe my proxies are just bad

Lmao
